### ISSUE TITLE
Kaspersky Virus Scanner detects Trojan

### ISSUE THREAD

**Issue by pschimmel** [ControlzEx/ControlzEx#105]
The Kaspersky virus scanner detects a trojan horse in ControlzEx.dll. I used the official MS nuget channel to get the latest version 4.2.2.4.

I'm confident it is a false positive, but you never know.

You can check that by using the online scanner:

https://virusdesk.kaspersky.de/

It is also detected by just uploading the latest .nupkg package available under releases

Here's the result:

![image](https://user-images.githubusercontent.com/9028723/75605371-82b17c80-5ae2-11ea-9670-b3362961f853.png)

**Comment by batzen** [comment]
Sorry for the late response. The versions distributed to nuget are built in the CI system so the build process is fully transparent. I had issues with false positives from AV software in snoop too recently. Will try to check with Kaspersky tomorrow and report the false positive to them.

**Comment by pschimmel** [comment]
Actually, I already sent in the nuget package to Kaspersky for evaluation.
Here's their response (02/29/20):

Hello,

Sorry, it was a false detection. It will be fixed.
Thank you for your help.

Best regards, Denis Sitchikhin, Malware Analyst
39A/3 Leningradskoe Shosse, Moscow, 125212, Russia Tel./Fax: + 7 (495) 797 8700 http://www.kaspersky.com https://securelist.com

__________________________________________

**Comment by batzen** [comment]
Thanks for reaching out to them 👍
