### ISSUE TITLE
HSL Documentation seems to be wrong

### ISSUE THREAD

**Issue by timunie** [ControlzEx/ControlzEx#107]
Hi @batzen ,

It seems that `Hue`is not in `[0;1]` but in `[0;360]`
https://github.com/ControlzEx/ControlzEx/blob/4d8107d4acc4e437d1bb63403b742130af492847/src/ControlzEx/Theming/HSLColor.cs#L86

P.S.: A really useful class :smile: :
![ColorPicker_Preview](https://user-images.githubusercontent.com/47110241/80377254-4fe5f380-889b-11ea-90f4-5547acd7f915.png)
The tinted colors were generated using HSL. Really easy to use. 

Happy coding,
Tim

**Comment by batzen** [comment]
Could you create a PR to fix it? 😁

**Comment by timunie** [comment]
sure, give me some days.

Have a nice evening

**Comment by timunie** [comment]
There are some more issues while converting from or to color. I am trying to provide some tests and fix this.

**Comment by batzen** [comment]
That would be great. As stated above the class i just copied the code. 😕
