### ISSUE TITLE
Safe detection of current theme

### ISSUE THREAD

**Issue by GeertvanHorrik** [ControlzEx/ControlzEx#108]
I am trying to move theme management in [Orchestra](https://github.com/wildgums/orchestra) to ControlzEx. However, when calling ChangeTheme, it is trying to detect the old theme. In this case, there is no old theme, but it still fails because of exceptions (failed to find resources).

Will figure out what's causing this. But even if this is a broken ResourceDictionary, shouldn't that be caught as exception and ignored?

**Comment by GeertvanHorrik** [comment]
![image](https://user-images.githubusercontent.com/1246444/80409004-6b1b2800-88c8-11ea-843a-94390d411ae1.png)

**Comment by GeertvanHorrik** [comment]
And would it be interesting to cache the result for ResourceDictionary instances that have a source?

**Comment by batzen** [comment]
I could add code to prevent that exception there, but it would surface somewhere else pretty quickly i guess. But it would, at least, prevent people from blaming ControlzEx.

> And would it be interesting to cache the result for ResourceDictionary instances that have a source?

What do you mean with that? Did you observe any performance issues?

**Comment by GeertvanHorrik** [comment]
Not really noticed performance issues, but seeing the same sources multiple times. And since it goes through all keys, it could be "slow"?

**Comment by GeertvanHorrik** [comment]
Without caching: [Orchestra.Theming.ThemeManager] [1] [METHODTIMER] ThemeManager.ChangeTheme took '96' ms

Let me fork and try with caching.

**Comment by GeertvanHorrik** [comment]
Once a theme has been loaded, it makes no difference (since it can find the theme dictionary super fast). But at app startup, when no theme is loaded (at least in Orchestra, but I see callstacks from Fluent.Ribbon as well), it goes through *all* existing resource dictionaries (and it seems per library theme provider).

I've written some caching (which does get hit, so that's a win, just not sure about the "trade-off"). I am happy to add error checking here as well.
