### ISSUE TITLE
Auto-Hide Taskbar retrieved position in WindowChromeBehavior is incorrect

### ISSUE THREAD

**Issue by mggx** [ControlzEx/ControlzEx#119]
I tried your solution and I'm very impressed how well the WindowChromeBehavior handles the Window Messages.

But there seems to be a problem with locating the correct position of the hidden taskbar.
The system thinks that the collapsed task bar on the right edge of the left monitor belongs to the left edge of the right monitor and vice versa. So you are using the wrong position in that case.

In this PR is a solution to that problem:
https://github.com/adobe/brackets-shell/pull/471/files (method: edgeHasAutoHideTaskBar)

**Comment by batzen** [comment]
Thanks for pointing this out.
I honestly never tested our code with different taskbar locations and multiple monitors.
Will try to reproduce and fix this.
