### ISSUE TITLE
Minor Issue: Debugger shows GlowWindow for Title

### ISSUE THREAD

**Issue by punker76** [ControlzEx/ControlzEx#140]
Imported from [MahApps](https://github.com/MahApps/MahApps.Metro/issues/3556) reported by @RickStrahl

## Describe the bug

When using a Debugger to attach externally or using a process viewer the Window title of a MetroWindow based application will show `GlowWindow` for the Title:

![image](https://user-images.githubusercontent.com/1374013/61581730-3cdf0f80-ab22-11e9-96c8-f754ac5b0ae6.png)

**To Reproduce**  
Run your MahAPps based application. Open a separate instance of Visual Studio and attach debugger. Search for your app's name in the process list.

**Expected behavior**  
This should probably show the actual Window title, rather than GlowWindow.

**Environment(please complete the following information):**
 - MahApps.Metro version v1.6.5]
 - OS: [e.g. Win10 1903]
 - Visual Studio [e.g. 2019 (16.1.4)]
 - .NET Framework [e.g. 4.6.2]

**Other**  
This is obviously a minor issue - it appears that Task Manager and Process Explorer are properly picking up the Window name, and the title must be something else that is getting picked up. Checking other WinForm and WPF apps they appear to leave this value empty, which would be preferable to the GlowWindow setting.

**Comment by RickStrahl** [comment]
I think this was fixed with the MahApps 2.0/ControlzEx 4.0(?)  releases.

Works now:

![image](https://user-images.githubusercontent.com/1374013/101231582-51a54000-3650-11eb-9642-674b0266296c.png)
