### ISSUE TITLE
Can not install NuGet package with version 4.X.X on a project that references .NETFramework,Version=v4.0

### ISSUE THREAD

**Issue by mbalous** [ControlzEx/ControlzEx#141]
## Describe the bug
Upon installing the ControlzEx NuGet package an error occurs.

## Actual behavior

An error occurs:

> Could not install package '_ControlzEx 4.0.0_'. You are trying to install this package into a project that targets '_.NETFramework,Version=v4.0_', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

## Environment

```
ControlzEx version: v4.x.x
Visual Studio: 2019 16.8.4
Target Framework: .NET Framework 4.0
```

**Comment by batzen** [comment]
Support for .net 4.0 was dropped years ago and was a community decision as you can see in #37

**Comment by mbalous** [comment]
Totally understandable.
I did not notice it at first in the breaking changes list.
https://github.com/ControlzEx/ControlzEx/releases?after=4.0.1

Thank you for your answer.
