### ISSUE TITLE
Error when building latest source code

### ISSUE THREAD

**Issue by pschimmel** [ControlzEx/ControlzEx#142]
Hi! 

I downloaded the source code for the latest release 4.4.0 and wanted to build it, without changing any settings.
However I can't build. I'm getting the following message from all three projects:
Error NU1701	Package 'Microsoft.Xaml.Behaviors.Wpf 1.1.31' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.0'. This package may not be fully compatible with your project.	ControlzEx.Showcase	C:\Users\patri\OneDrive - SPLM\ControlzEx-4.4.0\src\ControlzEx.Showcase\ControlzEx.Showcase.csproj

I also can't change the target framework in the properties of the projects.

**Comment by batzen** [comment]
That's because we used a rolling version for that dependency back then.
You have to change
`<PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.*" />`
to
`<PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.19" />`
in `Directory.Build.props`.

**Comment by pschimmel** [comment]
Thank you. It also worked when I downgraded Microsoft.Xaml.Behaviors.Wpf to 1.1.19 manually
