### ISSUE TITLE
.net5.0 labels disappear

### ISSUE THREAD

**Issue by angryLittleHamster** [ControlzEx/ControlzEx#143]
## Describe the bug
I have issues with text box labels disappearing and distortion of icons and tab labels when I quickly move the mouse to over over them.

## Steps to reproduce

(1) cloned the repo and compiled using Visual Studio 2019 v16.8.5.
(2) set the ControlzEx.Showcase as the startup project with the startup set to .net5.0-windows
(3) using the develop branch and run the ControlzEx.Showcase demo app 
(3) hover the mouse over various components on the screen (including tab labels)
(4) see text on tabs disappear and reappear sometimes

![2021-02-19-ControlzEX-issue](https://user-images.githubusercontent.com/38728608/108521928-d0e8fe00-72a6-11eb-845a-290399cd6a9b.png)

**Comment by punker76** [comment]
@angryLittleHamster Mh, works on my machine...

![image](https://user-images.githubusercontent.com/658431/108522980-b2e2c400-72cd-11eb-9194-1a616f4bcc31.png)

It looks like that this could be a graphic card issue. Can you check if you use latest stable graphics card dlls?

Another test could be to set the software rendering mode for WPF https://weblog.west-wind.com/posts/2017/feb/13/video-rendering-issues-for-wpf-windows#wpf-processrendermode

**Comment by angryLittleHamster** [comment]
thanks... found out it was a driver issue. I have updated the Intel UHD 630 graphics driver. Thought that Windows 10 would have updated that driver since I am always running the latest updates. This is now resolved and sorry for any troubles.

![DeviceInfo](https://user-images.githubusercontent.com/38728608/108529684-4b1d8080-72af-11eb-80b0-f135c269df34.PNG)
