### ISSUE TITLE
Import from MahApps: Accent color when Windows determines the accent color itself

### ISSUE THREAD

**Issue by punker76** [ControlzEx/ControlzEx#148]
https://github.com/MahApps/MahApps.Metro/issues/4156

## Describe the bug

Windows 10 has an option:

"Automatically select an accent color from my background".

This will select an accent color based on the background. But the color that MahApps / ControlzEx then sets is unfortunately not the same one that Windows then uses :/

Maybe the error is also in "ControlzEx". But since I only used MahApps I post it here :)

## Steps to reproduce

- create a project (.net 5 for example)
- include MahApps.Metro
- Overwrite "OnStartup" in the App.xaml.cs" and add the following:

```
ControlzEx.Theming.ThemeManager.Current.ThemeSyncMode = ControlzEx.Theming.ThemeSyncMode.SyncAll;
ControlzEx.Theming.ThemeManager.Current.SyncTheme();
```

- In Windows, set the "Automatically select an accent color from my background" setting.

- Compare accent colors

## Expected behavior

That the accent color MahApps.Metro uses is the same as in Windows.

## Actual behavior

The accent color MahApps.Metro uses is not the same as in Windows.
(Usually a little darker than the current color)

## Environment

```
MahApps.Metro version: v2.4.7
Windows build number: Win10 21H1 [Version 119043.1151]
Visual Studio: 2019 16.10.4
Target Framework: .Net Core 5.0 (but also happens in other versions)
```

## Screenshots

![sample](https://user-images.githubusercontent.com/65850767/127779661-e2dcba7a-b597-4b39-8c1a-a04e8ed088ec.png)

## Example project

[MahAccent.zip](https://github.com/MahApps/MahApps.Metro/files/6913084/MahAccent.zip)

Not really useful, but here it is when needed :)

**Comment by batzen** [comment]
@Rerago During testing on my machine i noticed that the colors match excatly.
So when i use "#FF2992CC" in the windows settings the color produced as accent color by the `WindowsThemeHelper` is also exactly "#FF2992CC".
So there might be something else causing the colors to differ, but i don't know why.
Could you try to run the ControlzEx showcase application and switch to the "Theming" tab there.
It should show all generated colors.

**Comment by Rerago** [comment]
@batzen 
When I use the default Windows 10 wallpaper:

https://wallpaperhub.app/wallpapers/1534

And the following settings in Windows:

![winsettings](https://user-images.githubusercontent.com/65850767/130399889-0b10e99c-a449-4dc9-9a7c-a7075e308ba7.png)

After "Sync now" I get the following in the "ShowCase":

![showcase](https://user-images.githubusercontent.com/65850767/130399933-5bd698a5-c495-46ac-a02a-2537274f990b.png)

FF064DF is detected but as you can see in the Windows settings, the accent color is much brighter and is "FF2997CC".

**Comment by punker76** [comment]
@batzen @Rerago That's really weird... If I click the "Automatically pick ..." checkbox then the synced accent color is not what I expect. I think it should be the second one (second screenshot) if I click the accent color.

_not expected color_
![2021-08-23_08h35_33](https://user-images.githubusercontent.com/658431/130401924-2e6954bb-b37d-49ec-8f57-4649e4fd622c.png)

_expected color_
![2021-08-23_08h35_17](https://user-images.githubusercontent.com/658431/130401958-f069e240-88d6-445a-8b66-825e4d627992.png)

**Comment by batzen** [comment]
So the wrong color only occurs when it's synced from the wallpaper and even disabling that sync afterwards leads to the wrong color... 
Will try to find out what's going on there.
