### ISSUE TITLE
Dead link in readme.md

### ISSUE THREAD

**Issue by binarycow** [ControlzEx/ControlzEx#153]
`readme.md` [contains a section](https://github.com/ControlzEx/ControlzEx#windowchromebehavior) on `WindowChromeBehavior`.

That section contains a dead link to `http://blogs.msdn.com/b/wpfsdk/archive/2008/09/08/custom-window-chrome-in-wpf.aspx`

Wayback machine gives this as a valid link: `https://web.archive.org/web/20150221141007/http://blogs.msdn.com/b/wpfsdk/archive/2008/09/08/custom-window-chrome-in-wpf.aspx`

**Comment by batzen** [comment]
Thanks for pointing this out.
