### ISSUE TITLE
Question about WindowChromeWindow getting around flickering behavior

### ISSUE THREAD

**Issue by d79ima** [ControlzEx/ControlzEx#154]
I have a WinForms control hosted inside a WPF window using WindowsFormsHost. The Window is also using a custom WindowChrome. The presence of the WindowsFormsHost causes annoying flickering of the window when you resize it.

It seems that in your WindowChromeWindow class you were able to solve this issue. Could you please shed some light on how you were able to do this? May be you could point out specific critical workaround for this in your code...
Thanks.

**Comment by batzen** [comment]
Sorry for answering so late.
One way to solve this is to cut off one pixel on one side during NCCALCSIZE or to do
```
if (PInvoke.GetWindowStyle(this.windowHandle).HasFlag(WINDOW_STYLE.WS_CAPTION))
{
    var rcBefore = Marshal.PtrToStructure<RECT>(lParam);
    PInvoke.DefWindowProc(this.windowHandle, (uint)uMsg, wParam, lParam);
    var rc = Marshal.PtrToStructure<RECT>(lParam);
    rc.top = rcBefore.top; // Remove titlebar
    Marshal.StructureToPtr(rc, lParam, true);
}
```

That should do the trick as far as i remember.
