### ISSUE TITLE
Remove dependency on XamlBehaviors?

### ISSUE THREAD

**Issue by bplatypus** [ControlzEx/ControlzEx#156]
## Describe the feature
I have the following issue using XamlBehaviors ([https://github.com/microsoft/XamlBehaviorsWpf/issues/108](https://github.com/microsoft/XamlBehaviorsWpf/issues/108)) and I don't know if the project is still alive as no one is replying to the issues for more than 1 year.

So I don't know if it would be possible to remove this dependency? I mean taking what's necessary from the xamlbehaviors and include it in your sources maybe.

**Comment by batzen** [comment]
I don't think it's a good idea to copy the copy as that would make all existing behaviors incompatible with the ones from ControlzEx and would also confuse users.

Have you tried to contact the listed MVPs?
If you haven't or haven't received a response, just let me know if I should give it a try.

**Comment by bplatypus** [comment]
> I don't think it's a good idea to copy the copy as that would make all existing behaviors incompatible with the ones from ControlzEx and would also confuse users.
> 
> Have you tried to contact the listed MVPs? If you haven't or haven't received a response, just let me know if I should give it a try.

thanks @batzen. If you already have contact with one of them, please give it a try! Thank you.
