### ISSUE TITLE
Syncronize from the currently added color themes.

### ISSUE THREAD

**Issue by DancePanda42** [ControlzEx/ControlzEx#158]
## Describe the bug
If I add two new themes, one for dark mode and one for light mode, each with a different accent color, and then call the following method:
```csharp
 SyncTheme(ThemeSyncMode.SyncWithAppMode)
```
The correct mode is used, but the color scheme from the App.xaml is used and neither of the two newly added ones.

## Steps to reproduce
```csharp
protected override void OnStartup(StartupEventArgs e)
{
    base.OnStartup(e);

    var dark = ThemeManager.Current.AddTheme(RuntimeThemeGenerator.Current.GenerateRuntimeTheme(ThemeManager.BaseColorDarkConst, Colors.IndianRed)!);
    var light = ThemeManager.Current.AddTheme(RuntimeThemeGenerator.Current.GenerateRuntimeTheme(ThemeManager.BaseColorLightConst, Colors.DarkRed)!);

    ThemeManager.Current.SyncTheme(ThemeSyncMode.SyncWithAppMode);
}
```

## Expected behavior

After I have created a new color scheme for each mode, it should also apply these.
This I can currently only achieve if I go this little detour.

```csharp
if (ThemeManager.Current.DetectTheme()?.BaseColorScheme == ThemeManager.BaseColorDark)
    ThemeManager.Current.ChangeTheme(this, dark);
else
    ThemeManager.Current.ChangeTheme(this, light);
```

## Actual behavior

The detected theme is used.
[ThemeManager](https://github.com/ControlzEx/ControlzEx/blob/845037327f16e57288a07f45496b2ea5d11295f9/src/ControlzEx/Theming/ThemeManager.cs#L1207)

## Environment

```
ControlzEx version: v5.0.1
Windows build number: Win10 21H2 [Version 10.0.19044]
Visual Studio: 2022 17.2.5
Target Framework: 6.0.400-preview.22301.10
```

**Comment by batzen** [comment]
A call to `ThemeManager.Current.SyncTheme(ThemeSyncMode.SyncWithAppMode);` won't change the color as long the there is a matching color for the new base color.

Why do you expect it to change the color?
Which color should be chosen?

**Comment by DancePanda42** [comment]
Due to the addition of the new color schemes, a more sensible workflow for me would be to select the new color from the last color schemes added.
Have I possibly overlooked a setting for a default color?

**Comment by batzen** [comment]
If you tell the theme manager to sync with the current app mode it just keeps the current color scheme and changes the base color.
Choosing the last added color scheme would be a very surprising behavior.

So the "default" color is the color scheme you have currently set.

**Comment by DancePanda42** [comment]
Yes ok, i understand that the last color added is set as default. Would probably cause confusion for other users.
I think this line will solve my problem in a relatively elegant way.
`ThemeManager.Current.ChangeTheme(this, WindowsThemeHelper.AppsUseLightTheme() ? lightTheme : darkTheme);`

Thank you for your time and quick response.
