### ISSUE TITLE
WindowChromeWindow - space around window except top

### ISSUE THREAD

**Issue by hxhgxy** [ControlzEx/ControlzEx#160]
## Describe the bug
When doing screen capturing, there are spaces at left, right and bottom. no space above. why? how to get rid of the space?

MahApps Metro Window is perfect except that cannot set CornerRadius to round or roundsmall. Why not override it from ControlzEx?

Thanks,
Tiger

## Environment

```
ControlzEx version: v4.x.x
Windows build number: Win10 1909 [Version 10.0.x.x]
Visual Studio: 2019 16.x.x
Target Framework: .Net Core 3.1 (v4.x.x)
```

**Comment by batzen** [comment]
Could you try the same with the ControlzEx 6.0 showcase application?
The problem shouldn't be present there.
Which would mean you'd have to wait for the next major version of MahApps.Metro to receive the fix.

**Comment by hxhgxy** [comment]
> Could you try the same with the ControlzEx 6.0 showcase application? The problem shouldn't be present there. Which would mean you'd have to wait for the next major version of MahApps.Metro to receive the fix.

sure, I am talking about ControlzEx i downloaded couple of days ago.

**Comment by batzen** [comment]
From where did you download it, as you wrote "ControlzEx version: v4.x.x" and the current dev version is 6.0.

**Comment by hxhgxy** [comment]
> From where did you download it, as you wrote "ControlzEx version: v4.x.x" and the current dev version is 6.0.

How to choose version 6.0? sorry, i'am new to github and WPF. I just downloaded version 5.0.1 and found the showcase works perfect. I have some problems with the source codes and trying to dig it out. 
There is no Microsoft.Windows.CsWin32 in version 5 anymore?

Thank you!

**Comment by batzen** [comment]
The default branch on github is "develop" where version 6.0 is developed.
The "main" branch contains version 5.

"Microsoft.Windows.CsWin32" is only used since version 6.

You can always grab the latest develop build from https://ci.appveyor.com/project/punker76/controlzex/build/artifacts
There you can also download the compiled showcase application.

Feel free to ask more questions if you need help.

**Comment by hxhgxy** [comment]
"Microsoft.Windows.CsWin32" is only used since version 6. - this means i downloaded the latest source codes? because i saw it.
I found that the window cornerradiuspreference: Round, RoundSmall etc. come from "Microsoft.Windows.CsWin32". This is the feature i liked by comparing to MahApps Window. But there some spaces arounding window except above, that is not as good as MahApps.
in the showcase v5.0.1 (i found it is same vs the link you put above), there is no space arounding window.

**Comment by batzen** [comment]
> But there some spaces arounding window except above, that is not as good as MahApps.

Could you attach images showing what you mean?
When i take a screenshot of the ControlzEx showcase window (via WIN + PRINT) there is no space around the window.

> in the showcase v5.0.1 (i found it is same vs the link you put above), there is no space arounding window.

The link leads to v6.0 and not v5.0.1. Support for Windows 11 rounded corners was only added in v6.0.

**Comment by hxhgxy** [comment]
![v5](https://user-images.githubusercontent.com/37101628/185769160-2d258977-3995-4bc3-bdc0-6a694273f639.png)
Showcase v5, the window border is the real border, there is no white space outside when doing screen capture.

![v6](https://user-images.githubusercontent.com/37101628/185769200-f55651f0-81a8-48cb-9ca6-7fd96dea7cf0.png)
Showcase v6, there is some gap between window border and the real one when screen capture.

![space](https://user-images.githubusercontent.com/37101628/185769249-0bf5aae0-ae57-406b-aaa8-43fe73016405.jpg)
the last one is running by source code project, same vs. the showcase v6.

maybe the reason is that v5 cannot set window corner? in order to improve it v6 has to use Microsoft.Windows.CsWin32 and result in the white spaces?

**Comment by batzen** [comment]
Which tool are u using to capture?
Using ALT + PRINT shortcut and pasting to Paint does not have the space around.

It looks like a bug in the tool you are using.

**Comment by hxhgxy** [comment]
You are right, it is right by using alt+prtscr. I use Weichat do screen capture previously. don't know why defferent between v5 and v6. anyway, it is not important now.
thank you very much!
