### ISSUE TITLE
Window Button Style

### ISSUE THREAD

**Issue by hxhgxy** [ControlzEx/ControlzEx#161]
## Describe the bug
Here are some findings, when I try to put buttons in resource dictionary for the window:
1. when i try to use the system command like below, the window button cannot be clicked anymore (double clike, the window will be maximized or normalized)

```
<Setter Property="Command"
 			Value="{Binding Source={x:Static SystemCommands.MinimizeWindowCommand}}" />
```
			
2. I try to apply the style below to window button, the IsPressed trigger works as expected, but the IsMouseOver trigger doesn't work

```
	<Style x:Key="WindowTitleButtonStyle"
	       TargetType="{x:Type Button}">
		<Setter Property="Focusable"
			Value="False" />
		<Setter Property="Background"
			Value="#32FFFFFF" />		
		<Setter Property="Width"
			Value="36" />
		<Setter Property="HorizontalContentAlignment"
			Value="Center" />
		<Setter Property="VerticalContentAlignment"
			Value="Center" />
		<!--<Setter Property="WindowChrome.IsHitTestVisibleInChrome"
			Value="True" />-->
		<Setter Property="IsTabStop"
			Value="False" />
		<Setter Property="Template">
			<Setter.Value>
				<ControlTemplate TargetType="{x:Type Button}">
					<Grid x:Name="LayoutRoot"
					      Background="Transparent">
						<Rectangle x:Name="ButtonBackground"
							   Fill="Yellow"
							   Opacity="0" />
						<Border x:Name="ButtonBorder"
							SnapsToDevicePixels="True">
							<ContentPresenter x:Name="TitileButtonContentPresenter"
									  Focusable="False" 
									  HorizontalAlignment="{TemplateBinding HorizontalContentAlignment}"
									  Margin="{TemplateBinding Padding}"
									  RecognizesAccessKey="True"
									  SnapsToDevicePixels="{TemplateBinding SnapsToDevicePixels}"
									  VerticalAlignment="{TemplateBinding VerticalContentAlignment}" />
						</Border>
					</Grid>

					<ControlTemplate.Triggers>
						<Trigger Property="IsMouseOver"
							 Value="True">
							<Setter Property="Opacity"
								Value="1"
								TargetName="ButtonBackground" />
						</Trigger>
						<Trigger Property="IsPressed"
							 Value="True">
							<Setter Property="Opacity"
								Value="0.6"
								TargetName="ButtonBackground" />
						</Trigger>
						<Trigger Property="IsEnabled"
							 Value="False">
							<Setter TargetName="TitileButtonContentPresenter"
								Property="Opacity"
								Value="0.5" />
						</Trigger>
					</ControlTemplate.Triggers>
				</ControlTemplate>
			</Setter.Value>
		</Setter>
	</Style>
```

and here are codes for applying the styles:
```
<UniformGrid Grid.Column="2"
						Columns="3">
	<Button Content=" - "
		Style="{StaticResource PART_WindowButtonMinimizeStyle}"
		tcBehaviors:NonClientControlProperties.HitTestResult="MINBUTTON"
		tcBehaviors:NonClientControlProperties.ClickStrategy="MouseEvent" />
	<Button Style="{StaticResource PART_WindowButtonMaximizeStyle}"
		IsEnabled="{Binding IsEnabled, ElementName=MaximizeButton}"
		tcBehaviors:NonClientControlProperties.HitTestResult="MAXBUTTON"
		tcBehaviors:NonClientControlProperties.ClickStrategy="MouseEvent" />
	<Button  Style="{StaticResource WindowTitleButtonStyle}"
		tcBehaviors:NonClientControlProperties.HitTestResult="CLOSE"
		tcBehaviors:NonClientControlProperties.ClickStrategy="MouseEvent" />
</UniformGrid>
```

It is acceptable for me to give up the system command. 
What I can try to fix the mouseover problem?

Thanks,
Tiger

## Environment

```
ControlzEx version: v6.x.x
Windows build number: Win11
Visual Studio: 2022
Target Framework: .Net 4.8
```

**Comment by batzen** [comment]
When you use `NonClientControlProperties.HitTestResult` with a value not equal `CLIENT` the controls don't get any regular mouse events.
That's a Windows limitation.

If you want to check if the mouse is over you can use `NonClientControlProperties.IsNCMouseOver` etc..
Commands also don't work on those controls as they don't receive all regular mouse events.

Also when using `NonClientControlProperties.HitTestResult="MINBUTTON"` there is no need to use `SystemCommands.MinimizeWindowCommand`.

**Comment by hxhgxy** [comment]
from the demo codes, I found that `tcBehaviors:NonClientControlProperties.IsNCMouseOver` can be used in style.triggers to trigger the background change.
Is there any technical to trigger animtion of the button content? for eample, when mouse over the close button, "x" rotate 90 by angle?

by the way, how can i ask question rather than raise up "Bug"? Looks I cannot change the label.

**Comment by batzen** [comment]
> Is there any technical to trigger animtion of the button content? for eample, when mouse over the close button, "x" rotate 90 by angle?

You can use the regular triggers on the mentioned attached property.

You can create a [discussion](https://github.com/ControlzEx/ControlzEx/discussions) instead of an issue if you only want to ask a question.

**Comment by hxhgxy** [comment]
![wpf animation](https://user-images.githubusercontent.com/37101628/187012135-aa6a7311-427d-428b-a99c-3afbb839e44d.png)

Animation triggered correctly above. However, when mouse is moved away from the button, button background opacity cannot change back to 0.
Any problem with my code?

Thanks!

**Comment by hxhgxy** [comment]
exitactions, i got it.
