### ISSUE TITLE
GlowBorder disapears on WindowChromeWindow if ResizeMode = NoResize

### ISSUE THREAD

**Issue by dcm99** [ControlzEx/ControlzEx#167]
## Describe the bug

When I set the ResizeMode of a WindowChromeWindow based Window to NoResize, the GlowBorder disapears. There is only a thin gray Border on the left, right and bottom.

## Steps to reproduce

Clone ControlzEx Repository develop Branch.
Start ControzEx.Showcase Demo Project
Set ResizeMode under the Options Expander to NoResize
Drag the Window a bit to force rendering

## Expected behavior

The GlowBorder should keep visible

## Actual behavior

The GlowBorder disapears

## Environment

```
ControlzEx version: 6.0.0-alpha0241
Windows build number: Win10 1607 [Version 10.0.x.x]
Visual Studio: 2022 17.3.6
Target Framework: .Net Core 3.
```

## Screenshots
![grafik](https://user-images.githubusercontent.com/33775782/196731651-a4f90d6c-c9b9-4818-9d70-5fd82fe1385f.png)
Border with ResizeMode = CanResize
![grafik](https://user-images.githubusercontent.com/33775782/196732185-277009b9-a0db-4ef3-a94f-164b50103326.png)
Border with ResizeMode = NoResize

**Comment by batzen** [comment]
@punker76 can you remember why we disable the glow when the window can't be resized? IMHO we should just show it and disable its ability to resize the window. If someone wants to hide it the depth can be reduced to 0.

**Comment by dcm99** [comment]
Thank you for looking into it.
I am not entirely sure if this is related to this issue or a different problem.
Currently it is a bit difficult to get a fully borderless window. I achieved this by setting the GlowColor to Transparent. I thought this was intended so, but after I ran into the problem with the ResizeMode, I checked in the MahApps.Metro Demo Application. There is a borderless Window Example, and in the current Dev Branch it shows a border.

![grafik](https://user-images.githubusercontent.com/33775782/196933218-adb8a328-05e1-49df-a470-7cbc6085b9f9.png)
Borderless Window by setting Glow Colors to transparent
![grafik](https://user-images.githubusercontent.com/33775782/196933555-7e9821dd-d17a-4a66-a3a4-8f2268b2541f.png)
Window without Border in MahApps.Metro

**Comment by batzen** [comment]
Setting the glow to transparent does not remove the glow.
If you want to remove the glow you either have to set the glow colors to `null` or set the depth to `0`.
Will fix the MahApps.Metro sample.

**Comment by dcm99** [comment]
Sorry my previous post was a bit misunderstanding.
what I meant was that currently it is not possible to get a borderless window. The only workaround is setting the Glow Color to the background color of the window. The glow border covers the border of the window and the window "appears" to be borderless. 
For me the workaround is ok. But if you fix the MahApps.Metro sample you see it yourself.

**Comment by batzen** [comment]
I might not understand what you are trying to achieve.
If you set the glow colors to null the glow is completely removed.

**Comment by dcm99** [comment]
I am trying to get a window without a visible border. But setting BorderThicknes to 0 is not working
![grafik](https://user-images.githubusercontent.com/33775782/197493234-650ead2c-7ba9-400f-9210-b11fa499d7aa.png)
there is a thin gray border visible. It is also visible if i set the content of the demo project to hidden, the border seems not to be part of any control.
My workaround was to set the glow color to the color of the background, but I dont think this is the intendet way to do so.
![grafik](https://user-images.githubusercontent.com/33775782/197493749-91151c27-3061-477f-a71d-b8b21be43f07.png)

**Comment by batzen** [comment]
Could you try to change the `WindowStyle` to `None`? I don't have a windows 10 machine to test it and it works on windows 11 without changing the window style.

**Comment by dcm99** [comment]
There is no visible change if i change WindowsStyle to None
tested on Windows 10 21H2 and Windows 10 1607 (LTSB)
![grafik](https://user-images.githubusercontent.com/33775782/197515377-cb81f2b0-7615-46a3-b776-2c6d34d5c39f.png)

**Comment by batzen** [comment]
Strange. Will check on a windows 10 machine after my vacation.

**Comment by punker76** [comment]
@batzen I think under Windows 10 there is still some chrome border visible, which shows the selected accent form the settings.

![image](https://user-images.githubusercontent.com/658431/197526932-62b221a2-3292-46ad-911b-4877844fc427.png)

**Comment by batzen** [comment]
Ok, that was enough info. Found it. ;-)
I guess we should discuss the consequences of what we'd have to change after my vacation @punker76.
