### ISSUE TITLE
Topmost not always working with WindowChromeWindow

### ISSUE THREAD

**Issue by dcm99** [ControlzEx/ControlzEx#168]
## First things first
I think it is a minor bug and it is easy to work around this. But after spending some time finding the reason for this behavior I thought it is good to mention it for later reference.
So feel free to archive this post
Keep up the good work
## Describe the bug

I have noticed a strange behavior of the WindowChromeWindow if my Application is not on Top (Minimized or some other Application has focus) and it tries to show a TopMost Messagebox. The Messagebox is shown in the Background and if Glow is active the Glow Border is Topmost.

## Steps to reproduce

Easiest way is to reproduce it in the ControlEx.Showcase app.
Clone ControlEx Repo Dev Branch
Go to MainWindow.xaml.cs in the ControlzEx.Showcase Project and change this code:
```C#
        private void ButtonOpenChildWindowOnClick(object sender, RoutedEventArgs e)
        {
            var window = this.CreateNewWindow();

            if (this.SetOwner.IsChecked == true)
            {
                window.Owner = this;
            }

            window.Show();
        }
```
to:
```C#
        private async void ButtonOpenChildWindowOnClick(object sender, RoutedEventArgs e)
        {
            await Task.Delay(3000);
            var window = new MainWindow
            {
                WindowStartupLocation = WindowStartupLocation.Manual,
                WindowStyle = this.WindowStyle,
                SetOwner =
                {
                    IsChecked = this.SetOwner.IsChecked
                },
                IsGlowTransitionEnabled = this.IsGlowTransitionEnabled,
                PreferDWMBorderColor = this.PreferDWMBorderColor,
                CornerPreference = this.CornerPreference,
                UseRadialGradientForCorners = this.UseRadialGradientForCorners,
                GlowDepth = this.GlowDepth,
                GlowColor = this.GlowColor,
                NonActiveGlowColor = this.NonActiveGlowColor,
                NCNonActiveBrush = this.NCNonActiveBrush,
                Topmost = true,
            };

            window.Show();
        }
```
1 . Start the Demo and hit the open Child window button.
![grafik](https://user-images.githubusercontent.com/33775782/198010901-5d7b08d4-f7a8-4735-94b1-8e5f88d2c6cc.png)
2. Minimize the main Window.
3. After three seconds the child Window appears in the background but the glow is Topmost

## Expected behavior

The Child-Window should show Topmost

## Actual behavior
![grafik](https://user-images.githubusercontent.com/33775782/198012697-a178586f-bdb3-4f31-8902-644102703d80.png)

The Problem is probably during initialization. If I Initialized the Window in the CreateNewWindow Method and return the window instance back to the Eventhandler like it is good practice, the Child Window is Topmost and it works
change code for working example:

```C#
        private MainWindow CreateNewWindow()
        {
            var window = new MainWindow
            {
                WindowStartupLocation = WindowStartupLocation.Manual,
                WindowStyle = this.WindowStyle,
                SetOwner =
                {
                    IsChecked = this.SetOwner.IsChecked
                },
                IsGlowTransitionEnabled = this.IsGlowTransitionEnabled,
                PreferDWMBorderColor = this.PreferDWMBorderColor,
                CornerPreference = this.CornerPreference,
                UseRadialGradientForCorners = this.UseRadialGradientForCorners,
                GlowDepth = this.GlowDepth,
                GlowColor = this.GlowColor,
                NonActiveGlowColor = this.NonActiveGlowColor,
                NCNonActiveBrush = this.NCNonActiveBrush,
                Topmost = true
            };

            return window;
        }

        private async void ButtonOpenChildWindowOnClick(object sender, RoutedEventArgs e)
        {
            await Task.Delay(3000);
            var window = this.CreateNewWindow();

            if (this.SetOwner.IsChecked == true)
            {
                window.Owner = this;
            }

            window.Show();
        }
```

## Environment

```
ControlzEx version: latest commit
Windows build number: Win10 1706 LTSB
Visual Studio: 2022 17.366
Target Framework: .Net Core 3.1 
```

**Comment by batzen** [comment]
@dcm99 Can't reproduce this on Windows 11...

**Comment by dcm99** [comment]
> @dcm99 Can't reproduce this on Windows 11...

today I install VisualStudio on my Windows 11 VM and try to confirm this. Maybe this is Windows 10 or Framework related

**Comment by dcm99** [comment]
I am also not able to reproduce this on a Windows 11 machine.
In my implementation, I toggle the Topmost Property at OnContentRendered of my Base Window. Then the Topmost is not ignored. It's not pretty but it works.
```C#
        /// <summary>
        /// On Windows 10 with <see cref="WindowChromeWindow"/> the Topmost Property is sometimes ignored. See: https://github.com/ControlzEx/ControlzEx/issues/168
        /// Toggle of the Topmost Property is a workaround
        /// </summary>
        protected override void OnContentRendered(EventArgs e)
        {
            base.OnContentRendered(e);
            if (!Topmost) return;
            Topmost = false;
            Topmost = true;
        }
```
