### ISSUE TITLE
Dark theme for system menu for WindowChromeBehavior

### ISSUE THREAD

**Issue by khdc** [ControlzEx/ControlzEx#173]
## Describe the feature

When running on Windows 10/11, it would be nice to show the system menu in the dark theme when the dark theme is selected.

**Comment by batzen** [comment]
The system menu is rendered by Windows itself.
Microsoft would have to change that.
Or we would have to implement our own ContextMenu, but that would cut off access to third party extensions.

Or did i miss some news and there is a Windows API or option to show a dark menu?

**Comment by khdc** [comment]
I know that you can use a API to make a Win32 window have a dark title bar, but I'm not sure if that also affects the system menu or not.

https://learn.microsoft.com/en-us/windows/apps/desktop/modernize/apply-windows-themes#enable-a-dark-mode-title-bar-for-win32-applications

I noticed that Visual Studio has a light system menu and it's using a similar technique as ControlzEx for their window, so maybe that's an indication we'll need to wait for more support from the Windows team.

Feel free to close this issue.
