### ISSUE TITLE
TabControlEx doesn't work corretcly

### ISSUE THREAD

**Issue by punker76** [ControlzEx/ControlzEx#18]
Issue comes from https://github.com/MahApps/MahApps.Metro/issues/2647

**Comment by Silv3rcircl3** [comment]
Any updates on this one? Looks like I hit the same bug as described in MahApps/MahApps.Metro#2647

**Comment by batzen** [comment]
Will fix this next week.

**Comment by batzen** [comment]
Next week became two years, but i finally worked on this and will push my changes for version 4.0.
