### ISSUE TITLE
How can I remove the border around a single border window?

### ISSUE THREAD

**Issue by bign0name** [ControlzEx/ControlzEx#181]
I want to keep my window as a single border window to keep animations, but I want to change the color of the border that is around the window, or remove it. NCActiveBrush and NCNonActiveBrush don't seem to do anything. Also for some reason the border isn't visible at the top of the window.
![Screenshot 2023-07-25 220441](https://github.com/ControlzEx/ControlzEx/assets/68962224/996603ea-3403-496c-90fa-c398cdd1fefc)

**Comment by batzen** [comment]
To change the color you have to set `GlowColor` and `NonActiveGlowColor`.
By setting those the native border color is changed on Windows 11 and on previous Windows versions it's "faked" by 4 separate windows that act as the border.

**Comment by bign0name** [comment]
Can I remove this border entirely?

**Comment by bign0name** [comment]
![image](https://github.com/ControlzEx/ControlzEx/assets/68962224/39d8a402-f1ca-40ff-b4b4-e6c6bd2b5b55)
How do u get around this error? Warning disable doesen't seem to work on this error.

**Comment by batzen** [comment]
https://github.com/ControlzEx/ControlzEx/blob/4c0f463a6fae9a446baf59dcee9772d1b3602c2a/src/ControlzEx/Native/PInvoke.cs#L41

That's the overload that should be invoked.
Don't know why that does not compile for you.
Are you sure you included/cloned/copied all the files from this repo?

**Comment by bign0name** [comment]
![image](https://github.com/ControlzEx/ControlzEx/assets/68962224/40187ab1-1ce7-4c3b-ad94-37b82ce3e0e1)
Sorry my bad, I removed what was not neccesary for window chrome window, I didn't realize however that glow window is what made the border. Not sure what to do about this though.

**Comment by bign0name** [comment]
Oh its not using the acutal PInvoke function and just the one from the class. How can I convert safehandle to HDC?

**Comment by batzen** [comment]
The method being called there should be generated by `Microsoft.Windows.CsWin32`, which is referenced by the project.

Converting from safehandle to HDC can be done through `new HDC(hdc.DangerousGetHandle())` as HDC only takes an IntPtr.

**Comment by batzen** [comment]
And GlowWindow is only responsible for a colored border on non Windows 11 operating systems.
It's not responsible for the system provided border.

**Comment by bign0name** [comment]
![image](https://github.com/ControlzEx/ControlzEx/assets/68962224/adc67efc-57d9-45ad-a587-884150543247)
How about converting HDC to safehandle?
![image](https://github.com/ControlzEx/ControlzEx/assets/68962224/e1c803f3-d1e4-477d-8d09-046772dc482f)
And where can I find DeleteDCSafeHandle?

**Comment by batzen** [comment]
It's either generated or part of the, hand written, PInvoke class.

It seems you deleted way too much code as the CI builds show: everything compiles fine without anything being missing.

**Comment by bign0name** [comment]
It works, could you just tell me how to convert HDC to SafeHandle?

**Comment by batzen** [comment]
All the `SafeHandle` instances used by ControlzEx are created by the generated code `Microsoft.Windows.CsWin32` from.
In case of an `HDC` the `SafeHandle` class should be `DeleteDCSafeHandle`.

**Comment by bign0name** [comment]
I was using a newer version of `Microsoft.Windows.CsWin32`. Now everything works.

**Comment by bign0name** [comment]
Sorry about that, that should've been first thing I checked.
