### ISSUE TITLE
NullReferenceException if Window closed in Window_Loaded

### ISSUE THREAD

**Issue by cocoon** [ControlzEx/ControlzEx#182]
## Describe the bug

I triggered a NullReferenceException in HandleBorderThicknessDuringMaximize when I directly close the MainWindow in the Window_Loaded method.

## Steps to reproduce

- Create a .net 6 wpf project
- add Mahapps Metro (currently 3.0.0-alpha0457)
- Change the Mainwindow to a MetroWindow
- attach a method to the Window Loaded event and just close it directly with:
`this.Close();`

## examle code
https://github.com/cocoon/ControlzExCrash

## Expected behavior

Processing should skip the null object

## Actual behavior

in HandleBorderThicknessDuringMaximize:
System.NullReferenceException: 'Object reference not set to an instance of an object.'

AssociatedObject = null

## Environment

```
ControlzEx version: v6.0.0.283
Windows build number: Win11 22H2 [Version 10.0.22621.1992]
Visual Studio: 2022 17.6.0
Target Framework: .Net 6.0
```

**Comment by batzen** [comment]
Thanks for reporting this!
