### ISSUE TITLE
System.MissingFieldException: 'Field not found: 'ControlzEx.Behaviors.WindowChromeBehavior.TryToBeFlickerFreeProperty'.'

### ISSUE THREAD

**Issue by Anakazel** [ControlzEx/ControlzEx#187]
With ver. 6.0 have a bug.
With 5.0.2 is works fine
System.MissingFieldException: 'Field not found: 'ControlzEx.Behaviors.WindowChromeBehavior.TryToBeFlickerFreeProperty'.'

**Comment by batzen** [comment]
That's because it was removed in v6.
You have to re-compile your code when updating major versions of ControlzEx.
Simply replacing the dll does not work for major versions.

**Comment by kamalkaushik1** [comment]
@batzen I'm also facing the same issue as mentioned by @Anakazel 
Exception thrown: 'System.MissingFieldException' in Microsoft.Xaml.Behaviors.dll
An exception of type 'System.MissingFieldException' occurred in Microsoft.Xaml.Behaviors.dll but was not handled in user code
Field not found: 'ControlzEx.Behaviors.WindowChromeBehavior.TryToBeFlickerFreeProperty'.

re-compile the code as well but no success.

**Comment by batzen** [comment]
Could you search your code for usages of the property?
If there is code using it, it shouldn't compile.
If there is no code using it, it would be nice if you could attach a repro.

**Comment by kamalkaushik1** [comment]
I have searched for this property in the code base but not found any reference.
Sorry I can't share the repro it is private

**Comment by batzen** [comment]
Are you using any other library that references ControlzEx?

**Comment by Khaos66** [comment]
I had this issue as well. I'm using `MahApps.Metro` which states 
<img width="179" alt="image" src="https://github.com/ControlzEx/ControlzEx/assets/4013009/1646def4-17b4-49b3-b067-c14d76ad365d">

**Comment by batzen** [comment]
Using ControlzEx 6.0 with MahApps.Metro 2.X is not possible.

**Comment by niprst** [comment]
The removal of this property is not mentioned in the [v6.0.0 release notes](https://github.com/ControlzEx/ControlzEx/releases) breaking changes.
You are right upgrade to a new major version can bring breaking changes, but we should be able to evaluate them from the release note and not trying and hope nothing is hidden.

**Comment by batzen** [comment]
@niprst You are totally right about the breaking changes section in the release notes. Just added it there.
