### ISSUE TITLE
Proposal to update ThemeManager.md with path requirements for theme resource files

### ISSUE THREAD

**Issue by quanljh** [ControlzEx/ControlzEx#189]
I've been attempting to utilize the ThemeManager and have followed the steps outlined in ThemeManager.md. 

I used XamlColorSchemeGenerator to generate my color schema files and created a ThemeProvider.cs to override the LibraryThemeProvider class.

```cs
public class ThemeProvider : LibraryThemeProvider
{
    public static readonly ThemeProvider DefaultInstance = new();

    /// <inheritdoc cref="LibraryThemeProvider" />
    public ThemeProvider() : base(true)
    {
    }
}
```
However, I encountered an issue where my color scheme files are not being recognized by ThemeManager. After investigation, I discovered that ThemeManager searches for resources in paths containing "/themes/", while my color scheme files are located at "themes/styles/colors/dark.orange.baml". 
This specific requirement isn't mentioned in the documentation, and I believe including it would be beneficial.

https://github.com/ControlzEx/ControlzEx/blob/d56493ff3ae6b7be1574a64092e18fe0dbd782d7/src/ControlzEx/Theming/LibraryThemeProvider.cs#L203-L206

**Comment by batzen** [comment]
Good catch. Will add it as soon as I have some spare time.

**Comment by batzen** [comment]
@quanljh I added a section. Could you have a look if that would have helped you?

**Comment by quanljh** [comment]
Yeah, LGTM, thanks!
