### ISSUE TITLE
Incorrect behavior when WindowChromeWindow  ResizeMode="CanMinimize"

### ISSUE THREAD

**Issue by zrt2399** [ControlzEx/ControlzEx#197]
## Describe the bug

WindowChromeWindow can still maximize when ResizeMode="CanMinimize"

## Environment

```
ControlzEx version: v6.0.0
Windows build number: Win10 22H2 [Version 19045.4894]
Target Framework: .Net 8.0
```

## Screenshots
![ScreenShot(9)](https://github.com/user-attachments/assets/f46be49a-1760-4b4d-8c0b-53db2cd3dd1b)
![ScreenShot(10)](https://github.com/user-attachments/assets/501a0cfc-e3e6-4886-8efa-8ddf954fddb9)

Thanks in advance for your help!

**Comment by zrt2399** [comment]
When will this change be updated to Nuget.

**Comment by batzen** [comment]
I hope to have time next week/weekend.

**Comment by zrt2399** [comment]
Thank you for the update on NuGet. 
I noticed that a reference to the System.Memory package has been added, but I couldn't find its usage in the project, this will add an extra dependency to my project.

**Comment by batzen** [comment]
That's a dependency we had to add to be able to continue to use Microsoft.CSWin32.
Will check if that's still needed as soon as I find some spare time.
