### ISSUE TITLE
Window chrome incorrect in windows 7

### ISSUE THREAD

**Issue by IDXGI** [ControlzEx/ControlzEx#200]
![image](https://github.com/user-attachments/assets/07437c30-9172-4d8b-8448-7dd556276673)
The top chrome is right(no chrome), but the left, right, bottom shows windows7 default chrome. 

## Environment

```
ControlzEx version: v7.0.0-rc0118
Windows build number: Windows7 Ultimate
Visual Studio: 2022 11.5
Target Framework: .Net 6
```

**Comment by batzen** [comment]
Windows 7, 8 and 8.1 are not supported anymore as their mainstream and extended supported ended.
