### ISSUE TITLE
[Suggestion] Change PackIconBase.Kind to DependencyProperty

### ISSUE THREAD

**Issue by Insire** [ControlzEx/ControlzEx#22]
Hi,

I'm currently working with [MaterialDesignInXamlToolkit](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit) and [MahApps.Metro](https://github.com/MahApps/MahApps.Metro) to create a nice looking UI for my app. Both of them use the PackIconBase from this project to provide nice looking icons. 

I quite like the idea and would like to propose to change the implementation of the Kind property of PackIconBase to be changed to a DependencyProperty, so i can change the icon during runtime via setters in xaml. I have a workaround to change the parent control via templating, but I'd prefer to be able to just change the Kind property directly.

Is this possible and a good idea?

**Comment by punker76** [comment]
@Insire The `Kind` property is already a DependencyProperty 😜 

https://github.com/ControlzEx/ControlzEx/blob/develop/src/ControlzEx/PackIconBase.cs#L40-L55

**Comment by Insire** [comment]
oh, lol my bad. Still weird that vs tells me to change it to a dependency property.
![devenv_2017-03-13_20-46-49](https://cloud.githubusercontent.com/assets/11455827/23872366/54b6544a-082e-11e7-8ea9-7380e0d00e2f.png)

**Comment by punker76** [comment]
@Insire Do you use the MahApps.Metro.IconPacks? Then this is a known issue by the MarkupExtensions.

**Comment by Insire** [comment]
I do indeed use MahApps.Metro.IconPack. Is there anything i can do?

**Comment by batzen** [comment]
Get and Set prefixes are meant for attached properties. I guess, really just guess, that it might be related to generics. VS2017 got worse than VS2015 on that topic.
If it works at runtime it's as bug in visual studio.

**Comment by Insire** [comment]
Yeah it works just fine, It  just triggers my OCD.

**Comment by punker76** [comment]
@Insire This here solves this error, but it's a breaking change, so it will be the v2.0 of IconPacks.

![image](https://cloud.githubusercontent.com/assets/658431/23874653/c1f3420e-0836-11e7-99ac-3d4caaf33ef3.png)

**Comment by Insire** [comment]
Sweet, i'll be looking forward to that. Do you have a ETA in mind already?

**Comment by batzen** [comment]
@punker76 what's causing the issue, if not generics?

**Comment by punker76** [comment]
@batzen The problem are the MarkupExtension which are in the same namespace. VS removes the MarkupExtension name from the PackIconXYZMarkupExtension, but that's now the problem for VS. If I put it to a different namespace with a different XmlnsDefinition then all works fine.

**Comment by punker76** [comment]
@Insire This week, maybe tomorrow...

**Comment by punker76** [comment]
@Insire I will close this here and solve the https://github.com/MahApps/MahApps.Metro.IconPacks/issues/29 and https://github.com/MahApps/MahApps.Metro.IconPacks/issues/30 at IconPacks repo.

**Comment by punker76** [comment]
@batzen Another solution could be renaming the extensions like `PackIconMaterialExtension` -> `PackIconMaterialExtExtension`.
