### ISSUE TITLE
Should we drop the .Net 4.0 support?

### ISSUE THREAD

**Issue by batzen** [ControlzEx/ControlzEx#37]
You know ControlzEx comes with .Net 4.0, .Net 4.5 and 4.6.2, but it was always been laborious.

So should we

👍 drop this
👎 leave this

.Net 4.0 support?

IMO I think this can be dropped...

Thx

(Idea taken from https://github.com/MahApps/MahApps.Metro/issues/3041)

**Comment by WilliamFeely** [comment]
Did this ever work with Windows XP?  If so, that might potentially be worthy of a 👎 if anyone is still targeting that OS.
