### ISSUE TITLE
Black screen in trying to use ControlzEx with transparent window background

### ISSUE THREAD

**Issue by PedroJrDev** [ControlzEx/ControlzEx#42]
I set up my window with WindowChromeBehavior and i tryed to use `[DllImport("user32.dll")]
            internal static extern int SetWindowCompositionAttribute(IntPtr hwnd, ref WindowCompositionAttribData data);` to make a transparent Window. But all i have is a black screen.

Is there a way to fix it?

**Comment by batzen** [comment]
You can't use a transparent window when using the WindowChromeBehavior as using a transparent window while using the behavior would cause performance issues.
