### ISSUE TITLE
Reference Expression.Blend.Sdk.WPF instead of shipping System.Windows.Interactivity manually

### ISSUE THREAD

**Issue by GeertvanHorrik** [ControlzEx/ControlzEx#44]
See https://www.nuget.org/packages/Expression.Blend.Sdk.WPF/

More and more WPF libs are referencing this one instead of delivering it themselves. This makes it easier to share the implementation and make sure no matter what package gets installed, they won't be fighting over the "System.Windows.Interactivity" assembly location.

**Comment by batzen** [comment]
I'd really like to do that.
But i have a few concerns about that package.

- It doesn't provide a project site (to file issues, request version updates etc.)
- It only has one owner which only has one package on nuget (if he decides to abandon the package we are out of luck)

**Comment by GeertvanHorrik** [comment]
Fully understand your concerns. But in all reality, Microsoft will never update the files again, their focus is on UWP.

**Comment by GeertvanHorrik** [comment]
And I don't believe it's a breaking change, just a dependency change in NuSpec.

**Comment by batzen** [comment]
I'll contact the owner of the package and ask if he could add @punker76, you (@GeertvanHorrik) and me as owners.
If he agrees, i'll create a new github repo which hosts the nuspec file and binaries used to create the package. Admins for that repo would then be every owner of the nuget package.
That way we ensure that the package can be updated at all times by enough people.

**Comment by batzen** [comment]
Still no response from the package owner...

**Comment by batzen** [comment]
As we are now referencing the OSS version of the library i consider this done. Do you agree @GeertvanHorrik ?

**Comment by GeertvanHorrik** [comment]
Fully agree!
