### ISSUE TITLE
A EntryPointNotFoundException exception occurred on the XP OS

### ISSUE THREAD

**Issue by DingpingZhang** [ControlzEx/ControlzEx#48]
I have a app that uses MetroWindow, which will crash when running on XP OS.  I found the reason is that MahApps.Metro calls the `NativeMethods.TryGetPhysicalCursorPos` method, but this method ([GetPhysicalCursorPos](https://msdn.microsoft.com/en-us/library/windows/desktop/aa969464(v=vs.85).aspx)) is only supported in Vista or newer OS. 

I think we can fix this with the following code:

(in ControlzEx\Microsoft.Windows.Shell\Standard\NativeMethods.cs Line 3211)

```csharp
        public static bool TryGetPhysicalCursorPos(out POINT pt)
        {
            bool returnValue = false;
            if (Utility.IsOSVistaOrNewer) // Doesn't call it if the OS isn't Vista or newer
                returnValue = _GetPhysicalCursorPos(out pt);
            else
                pt = new POINT();

            // Sometimes Win32 will fail this call, such as if you are
            // not running in the interactive desktop. For example,
            // a secure screen saver may be running.
            if (!returnValue)
            {
                System.Diagnostics.Debug.WriteLine("GetPhysicalCursorPos failed!");
                pt.X = 0;
                pt.Y = 0;
            }
            return returnValue;
        }
```

and

(in ControlzEx\Microsoft.Windows.Shell\Standard\NativeMethods.cs Line 3198)

```csharp
        public static POINT GetPhysicalCursorPos()
        {
            POINT pt = new POINT();

            if (Utility.IsOSVistaOrNewer && !_GetPhysicalCursorPos(out pt)) // Doesn't call it if the OS isn't Vista or newer
            {
                HRESULT.ThrowLastError();
            }

            return pt;
        }
```

If you allow, I will be happy to submit a pull request for it.

**Comment by batzen** [comment]
Support for .NET 4.0 will be dropped with the next version, so i guess adding fixes for XP doesn't really make sense.
