### ISSUE TITLE
Add GlowWindow from MahApps.Metro

### ISSUE THREAD

**Issue by batzen** [ControlzEx/ControlzEx#49]
We have to add the GlowWindow and related classes from MahApps.Metro to be able to provide a decent resize border around the window when using the WindowChromeBehavior.

Current progress can be tracked at https://github.com/ControlzEx/ControlzEx/tree/GlowWindow

@punker76 could you have a look at that?

**Comment by punker76** [comment]
Done with #46 

Relates to #46
