### ISSUE TITLE
Crashes with .NET 4.61: Could not load type 'System.Windows.DpiScale' in PresentationCore

### ISSUE THREAD

**Issue by RickStrahl** [ControlzEx/ControlzEx#50]
With the latest of Dragablz version (0.0.3.203) I'm seeing failures in a deployed application when users are running pre-4.62 versions of .NET. 

This is inside [Markdown Monster](https://markdownmonster.west-wind.com) and I'm seeing a lot of these errors in my analytics logs:

![image](https://user-images.githubusercontent.com/1374013/40703797-38b8b8d6-639b-11e8-8bbc-f57c34ca7ff5.png)

This started after installing the latest version of Dragablz  - none before the update.

MM is compiled against .NET 4.62 (need the new DPI Scaling features) but we bump down the supported runtime all the way to 4.52 to allow older versions of .NET to work (more info on why [here](https://weblog.west-wind.com/posts/2017/Jan/09/Faking-out-the-NET-Runtime-Version)). This has been working great without issues up to now.

So my question is - any idea what's changed that might be causing this issue and is there anything I can do about it?

**Comment by RickStrahl** [comment]
@punker76 replied with this:

@RickStrahl So my questions is, after I've read your article, is this the problem? https://github.com/ControlzEx/ControlzEx/blob/2a937e3e841cb0087cfdbb8f3b4caea7f781dd1b/src/ControlzEx/Microsoft.Windows.Shell/Standard/DpiHelper.cs#L116-L120
You use now implicite ControlzEx, compiled against .Net 4.6.2, but after faking to 4.5.2, this call will be still used and crashed now, cause the real installed version is pre 4.6.1...?

**Comment by RickStrahl** [comment]
This is definitely a side effect of my hackery with the SupportedVersion - just as I mention in the article. It can bite 'ya and it does in this case.

The issue is that Nuget package is using the 4.62 version so it gets the DpiScale call which is not available in 4.61. 

I can probably hack this via `packages.config` by adding the 4.5 version:

```xml
<package id="ControlzEx" version="3.0.2.4" targetFramework="net45" />
```

This should work.

Problem is the framework version will get hammered the next time a NuGet `update-package` happens and by then I will have forgotten all about this.

Luckily this is mostly an edge case anyway - there are only a handful of 

The code looks potentially fragile as it's essentially hardcoded for NET462. What happens if you target 472 in the future for example? You'd end up with old behavior unless you explicitly add the new target.

**Comment by batzen** [comment]
The code in DpiHelper is potentially fragile, but as there are only 4 code blocks leveraging `#if` it really not that fragile as we know about these locations and update them on .net upgrades.
It's already on my list to improve the checks when we remove .NET 4.0 support.
I wish compile time constants could use operators like `#if NET_VERSION >= 4.6.2`.

What's your suggestion on how to fix this issue? 

I don't have any ideas.

**Comment by RickStrahl** [comment]
I don't think there's a clean solution to this and I don't expect you fix it. 

My question was more about why this is happening and I think I can at least temporarily fix this with an explicit package requirement (until I forget). 

In the not so far future I plan on moving the baseline to .NET 4.71/2 so this will no longer be an issue anyway. At this point I see ~85% on 4.7 or later. Once that crosses 90% I pull the plug on 4.6 and require 4.7.

I'd really love to use 4.72 so there's full support for .NET Standard 2.0 without requiring extra assembly imports, but that unfortunately will take a while...

**Comment by batzen** [comment]
I just happens because we use parts from .net 4.6.2 and your software is allowed to run with a lower version of .net. Never expected someone to do that to get support for per monitor dpi support while still not requiring .net 4.6.2 to be installed. ;-)

May i ask how you monitor the usage of your software? Can't tell that from the screenshot you attached.
