### ISSUE TITLE
Maximize problem when using glass frame

### ISSUE THREAD

**Issue by jizc** [ControlzEx/ControlzEx#51]
I'm experiencing an issue when maximizing windows (both in my application and in the showcase). When selecting `NoneWindowStyle` everything works as expected. However when using `NoneWindowStyleWithGlassFrame`, every other time I maximize the window, the top 8 pixels of the window are cut off.

![image](https://user-images.githubusercontent.com/1404846/40802186-340b0070-6515-11e8-97d8-c969b2db0c77.png)

More or less helpful info:
- I'm using Windows 10 - 1803.17134.48 - x64
- I have a 2 monitor setup, the dpi scale on both is 1 (the problem persists if I change the dpi, but the amount of pixels cut of increases with the scale i.e. 12 pixels cut off when using 1.25 dpi scale)
- I'm seeing the same effect when maximizing on both monitors
- The problem goes away if I enable `IgnoreTaskbarOnMaximize`
- If I maximize the window by dragging it to the top of the monitor, it always works as expected
- It happens consistently in all 3 showcases (NET40, NET45, NET462)
- The problem persists in the [WindowChromeNext](https://github.com/ControlzEx/ControlzEx/tree/WindowChromeNext) branch
- `lParam` in `_HandleNCCalcSize` is providing a different `Top` and `Bottom` when the problem occurs and setting it to `rcWork` is not correcting it (`Top` is -8 when it's working, 8 when the problem occurs)
- If I step through the code when maximizing, the problem does not occur

I've been trying to solve this for hours and I'm at the end of my rope, so I hope you can help 😄

**Comment by batzen** [comment]
I planned to deprecate GlassFrameThickness as it causes the issues you are encountering and i won't use it in Fluent.Ribbon anymore as soon as the GlowWindow branch is merged here...

**Comment by jizc** [comment]
Ah, ok, I understand. It's a minor thing I guess, I just prefer the look of the glass frame to that of GlowWindow. But I can learn to live with it 😉

**Comment by batzen** [comment]
What don't you like about the GlowWindow?

**Comment by jizc** [comment]
Just that the look is not exactly like the native window shadows. I've been using it for a long while through the MetroWindow that's part of MahApps.Metro. But I'm no longer using any of the other controls in that library, so I wanted to remove my dependency on it.

I tend to prefer having my windows look as native as possible, except for making my my own title bar. I think the native shadows look more polished somehow. But I suppose with some tweaking I'd be able to make GlowWindow look pretty much the same.

**Comment by batzen** [comment]
The GlowWindow in this repo is slightly different from the one in MahApps.Metro as you can control the width/height of it.
Maybe give it a try and report back any issues you encounter when trying to reproduce the native shadow. Maybe we can further improve our GlowWindow by your feedback.

**Comment by jizc** [comment]
Nice, I'll give it a try 👍 Thanks for that fast and helpful responses!

**Comment by batzen** [comment]
You are welcome. ;-)
