### ISSUE TITLE
_HandleNCACTIVATE is causing child windows to not be interactive

### ISSUE THREAD

**Issue by jizc** [ControlzEx/ControlzEx#56]
The change in [this commit](https://github.com/ControlzEx/ControlzEx/commit/b59796ebeaa3b71b3a8a4ac26ddb7bfce1d6e706) is causing child windows to not be interactive. Mouse over still works, but no mouse clicks get through (with the exception of dragging the title bar). After reverting that specific change, it works as expected again.

### To reproduce
1. Clone test repo https://github.com/jizc/ControlzEx
2. Run Showcase
3. Click `OPEN CHILD WINDOW` button at the bottom
4. Try to click any button in the child window

### Expected behavior
- The buttons in the child test window should change the color of the window's background
- Should be able to close child window by clicking the close button in the top-right corner

**Comment by batzen** [comment]
Already reverted that change on my machine. Just forgot to push my changes... Will push later.

**Comment by batzen** [comment]
Pushed my changes.
