### ISSUE TITLE
[BUG] how to build ?

### ISSUE THREAD

**Issue by ikeas68** [ControlzEx/ControlzEx#59]
i try to build
but i have problem 
i download a zip 
i try to open sln with vs2017
but 2 project are not loaded
when i tru to load i have  message "MSBuild.Sdk.Extras" not install

how i can install it ?

**Comment by batzen** [comment]
Which version of VS2017 do you have?
Do you have the .net core sdk installed?

**Comment by ikeas68** [comment]
i have vs 2017 15.5.6
normaly i have install .net core sdk with visual studio

Le lun. 6 août 2018 à 15:18, Bastian Schmidt <notifications@github.com> a
écrit :

**Comment by batzen** [comment]
Could you try to run Build.ps1 and see what it says?

**Comment by ikeas68** [comment]
i seem to have a problem with my compagny proxy
i check it and i send a message for you after if you want

Le lun. 6 août 2018 à 17:34, Bastian Schmidt <notifications@github.com> a
écrit :
