### ISSUE TITLE
Fully transparent window

### ISSUE THREAD

**Issue by Pekshev** [ControlzEx/ControlzEx#65]
I write plug-ins CAD and BIM in which I used Mahapps.Metro. But in view of the fact that conflicts often occur with other plugins that also use Mahapps.Metro, I decided to make my library based on Mahapps.Metro.
I have introduced the ControlzEx library into my library:
![image](https://user-images.githubusercontent.com/12638819/47482269-bde0d300-d83e-11e8-959b-7d6710eaa4ff.png)

Everything turned out, except for one problem - if I turn on transparency (AllowsTransparency="True" Opacity=".8") in the test project, then the window appears completely transparent. However, it appears and when I could grab it with the mouse and maximize it to the full screen, it appeared! And after it was curled back to normal, it continued to work normally.

In my window, I removed the GlowWindowBehavior and left only BorderlessWindowBehavior and WindowsSettingBehaviour. 
![image](https://user-images.githubusercontent.com/12638819/47482346-f7194300-d83e-11e8-82ac-d4e5096b0ac4.png)

Tell me where to look for the problem? It seems to me that the problem is somewhere in BorderlessWindowBehavior

**Comment by punker76** [comment]
@Pekshev `AllowsTransparency="True"` is not supported/allowed together with `BorderlessWindowBehavior` because of several reasons like performance and clear type issues. If you want a transparent window then you can not use this lib and must implement your window with the official `WindowChrome` (and it's side effects) together with `AllowsTransparency="True"`.

**Comment by Pekshev** [comment]
But it work in Mahapps.Metro =) Why so? All the same is used there.

**Comment by punker76** [comment]
@Pekshev MahApps doesn't set `AllowsTransparency="True"`. Just a note about the versions, MahApps v1.6.5 uses an older ControlzEx then MahApps v2.0 alpha.

**Comment by Pekshev** [comment]
> @Pekshev MahApps doesn't set `AllowsTransparency="True"`. Just a note about the versions, MahApps v1.6.5 uses an older ControlzEx then MahApps v2.0 alpha.

Do not quite understand you. I took a demo project, turned on the transparency and everything works fine.
![image](https://user-images.githubusercontent.com/12638819/47485112-1ebfd980-d846-11e8-872f-3036f57a94db.png)

In my project I took the code from your library (just not all), which means it corresponds to version 2.0.0-alpha
It's easier to forget about transparent at all))

**Comment by punker76** [comment]
This will be possible with the new v6 release.
