### ISSUE TITLE
VS 2017 Cannot Load projects 

### ISSUE THREAD

**Issue by hxhgxy** [ControlzEx/ControlzEx#69]
I downloaded the source code and try to open it in VS 2017, however, projects cannot be loaded. and there is noing in the Output pane.

what I can do?

thanks!
Tiger

For information, MetroWindow, MaterialDesign source codes downloaded from GitHub works fine on my computer.
Fluent.Ribbon has the same issue too.

![controlzex](https://user-images.githubusercontent.com/37101628/51153875-bd3f6200-18ac-11e9-895a-1a281724222f.PNG)

**Comment by batzen** [comment]
You have to use VS2019. As we (ControlzEx, MahApps.Metro and Fluent.Ribbon) already support the preview versions of .net core 3.0.

**Comment by punker76** [comment]
@hxhgxy @batzen I have updated the [README](https://github.com/ControlzEx/ControlzEx#quick-started-for-developers)
