### ISSUE TITLE
Maximizing a window with a WindowChromeBehavior.IgnoreTaskbarOnMaximize set to false makes it unusable

### ISSUE THREAD

**Issue by jeuxjeux20** [ControlzEx/ControlzEx#70]
Hello,

I have some kind of issue with my custom window and `WindowChromeBehavior`.
When not maximized, it runs fine and resizes fine, however, when maximized, a previously fixed problem appears again: 
![image](https://user-images.githubusercontent.com/16415180/51278160-27095a00-19da-11e9-9964-6133a896b30e.png)
The window gets stuck to the top left corner and is passing clicks through other windows.
This only happens when `IgnoreTaskbarOnMaximize` is set to `false`.
This does not happen with a normal window, only with my custom one.
Here is a cut version of the template: 
```xaml
<ControlTemplate TargetType="{x:Type controls:ThemedWindow}">
    <Grid>
        <AdornerDecorator x:Name="Adorner">
            <Grid Background="{TemplateBinding Background}">
                <Grid.RowDefinitions>
                    <RowDefinition Height="20"/>
                    <RowDefinition Height="*"/>
                </Grid.RowDefinitions>
                <Grid.ColumnDefinitions>
                    <ColumnDefinition Width="*"/>
                    <ColumnDefinition Width="Auto"/>
                </Grid.ColumnDefinitions>
                <Grid x:Name="PART_MoveArea" Background="Transparent">
                    <Viewbox VerticalAlignment="Center" HorizontalAlignment="Left" Margin="10 1">
                        <TextBlock Text="{TemplateBinding Title}" />
                    </Viewbox>
                </Grid>
                <StackPanel Grid.Row="0" Grid.Column="1" Orientation="Horizontal">
                    <!-- Title bar buttons -->
                </StackPanel>
                <ContentPresenter Grid.Column="0" Grid.Row="1" Grid.ColumnSpan="2" Margin="2"/>
            </Grid>
        </AdornerDecorator>
        <ResizeGrip x:Name="WindowResizeGrip"/>
        <!-- + usual props -->
        <Border BorderThickness="{TemplateBinding BorderThickness}"
                                BorderBrush="{TemplateBinding BorderBrush}" 
                                Background="{x:Null}"
                                HorizontalAlignment="Stretch" VerticalAlignment="Stretch"/>
    </Grid>
    <!-- Triggers -->
</ControlTemplate>
```
And here is the WindowChromeBehavior:
```cs
new WindowChromeBehavior
{
    IgnoreTaskbarOnMaximize = false,
    ResizeBorderThickness = new Thickness(5),
    KeepBorderOnMaximize = true,                  
};
```

**Comment by batzen** [comment]
Which version of controlzex are you using?

**Comment by jeuxjeux20** [comment]
4.0.0-alpha0222

**Comment by batzen** [comment]
I just cloned your project, switched to the ui-updates branch, built and ran the project.
Maximized the window without problems with and without `IgnoreTaskbarOnMaximize`.
Do you have any local modifications which might cause the issue?

**Comment by jeuxjeux20** [comment]
Thanks for building my project, I can't think of much modifications other than i'm building it on visual studio 2019. That's really weird :/

**Comment by batzen** [comment]
Which windows version are you using?

**Comment by jeuxjeux20** [comment]
I built it on Windows 10 October Update, does the same bug in a Windows 7 VM, with a transparent background this time.

**Comment by batzen** [comment]
I am also running win 10 october update and vs2019.
Could you attach the binaries your build creates to this issue?

**Comment by jeuxjeux20** [comment]
Here are the binaries:
[Debug.zip](https://github.com/ControlzEx/ControlzEx/files/2775418/Debug.zip)
(Built as debug)

**Comment by batzen** [comment]
Still can't reproduce the issue...
Any DPI settings you changed?
What kind of GPU do you have?
Do you have any software installed that changes rendering settings on windows?
Does this also happen with the showcase application from ControlzEx?

**Comment by jeuxjeux20** [comment]
Even more weirder then :v, i didn't change my DPI and I have an NVIDIA GeForce 1050, i'm going to test the showcase app soon

**Comment by jeuxjeux20** [comment]
The showcase works fine, could it be a problem from the custom window template?

**Comment by jeuxjeux20** [comment]
Oh, the problem was fixed by override the dependency property metadata instead of putting it in the style, i'm terrible at making custom controls XD

**Comment by batzen** [comment]
Which metadata on which dependency property?

**Comment by jeuxjeux20** [comment]
Oh forgot to mention, `AllowTransparencyProperty` and `WindowStyleProperty`

**Comment by batzen** [comment]
So i guess we should add some kind of guard to prevent such issues.
@punker76 Should we add a check for WindowStyle = None in OnAttached and throw an exception if it's not already set to None instead of setting it to None there?
