### ISSUE TITLE
It is not possible to switch in full screen mode

### ISSUE THREAD

**Issue by cpCr4zy** [ControlzEx/ControlzEx#76]
It is not possible to switch in full screen mode. See attached sample project
Step to reproduce:
-	Start the test app
-	Click on „Enter fullscreen mode“
-	The task bar is still visible

Expected outcome: the task bar is covered by the window

[SystemMenuBug.zip](https://github.com/ControlzEx/ControlzEx/files/3207769/SystemMenuBug.zip)

**Comment by punker76** [comment]
@cpCr4zy Simply set the `IgnoreTaskbarOnMaximize` property of `WindowChromeBehavior` to true.

```xaml
<controlzex:WindowChromeBehavior IgnoreTaskbarOnMaximize="True" ResizeBorderThickness="6"/>
```
