### ISSUE TITLE
Xaml behaviors for .net core wpf

### ISSUE THREAD

**Issue by HanbGao** [ControlzEx/ControlzEx#79]
when use it  will show the warning below:

Warning	NU1701	Package 'Microsoft.Xaml.Behaviors.Wpf 1.0.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v3.0'. This package may not be fully compatible with your project.

How to fix it?

**Comment by batzen** [comment]
You'll have to ask that question at https://github.com/microsoft/XamlBehaviorsWpf
They already have an open PR for that at https://github.com/microsoft/XamlBehaviorsWpf/pull/20#issuecomment-497236421

**Comment by HanbGao** [comment]
> You'll have to ask that question at https://github.com/microsoft/XamlBehaviorsWpf
> They already have an open PR for that at [microsoft/XamlBehaviorsWpf#20 (comment)](https://github.com/microsoft/XamlBehaviorsWpf/pull/20#issuecomment-497236421)

Thanks.There seemed to be no choice but to wait

**Comment by batzen** [comment]
Seems so. But as it's "just" a warning you should be able to ignore it.

**Comment by HanbGao** [comment]
> Seems so. But as it's "just" a warning you should be able to ignore it.


More than just this.If publish a single-file executable with dotnet publish（https://devblogs.microsoft.com/dotnet/announcing-net-core-3-0-preview-5/），the application will get an error and not run

**Comment by batzen** [comment]
You should add that comment to the PR i mentioned as that's really a blocking issue then.

**Comment by HanbGao** [comment]
> You should add that comment to the PR i mentioned as that's really a blocking issue then.
I have submitted comments on these issues
