### ISSUE TITLE
Borderless Window Style goes wrong

### ISSUE THREAD

**Issue by punker76** [ControlzEx/ControlzEx#80]
Imported from https://github.com/MahApps/MahApps.Metro/issues/3516

**Describe the bug**
Original window style can be seen when switch window in Win7.

**To Reproduce**
1. Open demo application. Notice the top-left corner and top-right corner of window.
2. Open VS window.
3. Switch between VS window and main window. Notice the style of VS window.
5. Maximize and restore VS window. Switch between windows. Style won't change anymore.

**Expected behavior**
CornerRadius should be 0. And style of window should not change.

**Screenshots**
[Expected]
![Expected](https://user-images.githubusercontent.com/12225840/58779481-a9508e80-8608-11e9-9a82-8d170e7bf201.PNG)    
[Actual]
![Actual](https://user-images.githubusercontent.com/12225840/58779501-b5d4e700-8608-11e9-9840-3a897aa9aeaf.PNG)    
[Screen record]
![record](https://user-images.githubusercontent.com/12225840/58779883-b9b53900-8609-11e9-8eba-9ee59c8a1f8c.gif)

**Environment(please complete the following information):**
 - MahApps.Metro version [latest code in develop branch]
 - OS: [Win7 SP1]
 - Visual Studio [dotenet core 3.0 preview 5]
 - .NET Framework [4.6]

**Additional context**
This only happen in some real machines. But it can be easy reproduced on virtual machine. And once you set Performance Options -> Visual Effects -> Adjust for best performance. This problem will no longer exist.

**Note**
@wunianqing This is related to the new/changed implementation of the borderless behavior in ControlzEx v4.0 alpha.

/cc @batzen I can reproduce this in a Win7 test VM, but didn't know how to solve this. (Another effect is while changing focus from Window to another Window is that the win 7 aero theme is shown  for one second. I don't know if I want to fix this... 🙈  )

![2019-06-03_12h50_42](https://user-images.githubusercontent.com/658431/58797475-5d99e700-8600-11e9-884b-261a2ce5f21a.png)

![mahapps_controlzex_win7](https://user-images.githubusercontent.com/658431/58797679-e57ff100-8600-11e9-9cca-07ac2b70fb11.gif)

**Comment by wunianqing** [comment]
Hi, @batzen 
I noticed that window style goes right after you dragged window. And I took a look at what happen when drag. I found this in `WindowChromeBehavior.MessageHandling.cs` line 667.
```cs
        /// <SecurityNote>
        ///   Critical : Calls critical methods
        /// </SecurityNote>
        [SecurityCritical]
        private IntPtr _HandleENTERSIZEMOVEForAnimation(WM uMsg, IntPtr wParam, IntPtr lParam, out bool handled)
        {
            if (this.MinimizeAnimation)// && _GetHwndState() != WindowState.Minimized)
            {
                /* we only need to remove DLGFRAME ( CAPTION = BORDER | DLGFRAME )
                 * to prevent nasty drawing
                 * removing border will cause a 1 off error on the client rect size
                 * when maximizing via aero snapping, because max by aero snapping
                 * will call this method, resulting in a 2px black border on the side
                 * when maximized.
                 */
                this._ModifyStyle(WS.CAPTION, 0);
            }
            handled = false;
            return IntPtr.Zero;
        }
```
But in the same file line 897, the same condition `if (this.MinimizeAnimation)` does a different action.
```cs
        /// <SecurityNote>
        ///   Critical : Calls critical methods
        /// </SecurityNote>
        [SecurityCritical]
        private void _UpdateFrameState(bool force)
        {
            if (IntPtr.Zero == this.windowHandle 
                || this.hwndSource.IsDisposed)
            {
                return;
            }

            if (force)
            {
                if (this.hwndSource.IsDisposed)
                {
                    // If the window got closed very early
                    return;
                }

                if (this.MinimizeAnimation)
                {
                    // allow animation
                    this._ModifyStyle(0, WS.CAPTION);
                }
                else
                {
                    // no animation
                    this._ModifyStyle(WS.CAPTION, 0);
                }

                //if (this.AssociatedObject.IsLoaded)
                {
                    NativeMethods.SetWindowPos(this.windowHandle, IntPtr.Zero, 0, 0, 0, 0, SwpFlags);
                }
            }
        }
```
I removed the if statement and only keeped `this._ModifyStyle(WS.CAPTION, 0);`. This problem gone. But I think this will cause other problems.
Hope this helps you.

**Comment by batzen** [comment]
The fix worked on my win7 VM.
Could you both please re-test if it's really fixed? @punker76 @wunianqing

**Comment by punker76** [comment]
> The fix worked on my win7 VM.
> Could you both please re-test if it's really fixed? @punker76 @wunianqing

The good old `DwmIsCompositionEnabled` 🙈

**Comment by batzen** [comment]
That was the easiest way to detect if we are running on windows 7... As it's the last version where DWM composition is optional ;-)

**Comment by punker76** [comment]
@batzen Works on my machines™ 👍
