### ISSUE TITLE
Crash in DeactivateTaskbarFix

### ISSUE THREAD

**Issue by NeomMob** [ControlzEx/ControlzEx#81]
I have daily users getting crash in the following method (I am not using directly ControlzEx but Mahapps)

- ControlzEx : 3.0.2.4
- Mahapps : 1.6.5.1
- VS 2017
- Framework 4.6.2
- Windows 6.3.17134.0 (for this one but happens on multiple version)

Anything I can do to at least trap it and avoid a crash?

```
System.ComponentModel.Win32Exception: El identificador de la ventana no es válido
   en ControlzEx.Behaviors.WindowChromeBehavior.DeactivateTaskbarFix(IntPtr trayWndHandle)
   en ControlzEx.Behaviors.WindowChromeBehavior.HandleMaximize()
   en ControlzEx.Behaviors.WindowChromeBehavior.AssociatedObject_StateChanged(Object sender, EventArgs e)
   en System.EventHandler.Invoke(Object sender, EventArgs e)
   en System.Windows.Window.OnStateChanged(EventArgs e)
   en System.Windows.Window.WmSizeChanged(IntPtr wParam)
   en System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   en System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   en MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   en MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   en System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   en System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by mgnslndh** [comment]
I get this as well but it seems like the `WindowChromeBehavior` class has been refactored because the `DeactivateTaskbarFix` is no longer there. According to @punker76 there will be a new release of ControlzEx  as soon as the next version of MahApps is ready.

**Comment by NeomMob** [comment]
Thanks @mgnslndh for the investigation. @punker76 is there any workaround meanwhile?

**Comment by NeomMob** [comment]
Anything that we can do to fix that impacting issue when using Mahapps 1.6.5?

**Comment by mgnslndh** [comment]
@NeomMob Not that I know of. The new release of ControlzEx is not "nuget" compatible with MahApps 1.6.5. Not sure if that is possible or even desirable to work around.

**Comment by NeomMob** [comment]
@mgnslndh I have no issue to create custom build and do not have a nuget but I have multiple daily users encountering crashes for that reason.

**Comment by mgnslndh** [comment]
You might want to make a branch and try to upgrade MahApps to latest alpha 2.0.0 and see if that works. You will get the new ControlzEx release then. Not sure how stable MahApps 2.0.0 alpha is. Maybe ask @punker76 if 2.0.0 is near release or unstable.

https://www.nuget.org/packages/MahApps.Metro/2.0.0-alpha0455
