### ISSUE TITLE
[FeatureRequest] Enable TextTrimming on ContentControlEx

### ISSUE THREAD

**Issue by timunie** [ControlzEx/ControlzEx#89]
I am using `ContentControlEx` to render a Text where all the content is uppercase, while the string itself is not. The Control is a Header for a `ListView`, so the `GridColumn` can be resized. I would like to have the text trimmed when the `GridColumn` is too small to render all the text, as the `TextBlock` does. Is there a way to implement this feature? 

Current Implementation: 
![image](https://user-images.githubusercontent.com/47110241/64766568-7c384400-d546-11e9-8ea0-6f5d04d50c48.png)

What I am looking for:
![image](https://user-images.githubusercontent.com/47110241/64766754-d6d1a000-d546-11e9-8406-9bbefab8e5a4.png)

```
<TextBlock Grid.Column="4" Text="RESPONIBLE" TextTrimming="CharacterEllipsis" />
<TextBlock Grid.Column="5" Text="PROGRESS" TextTrimming="CharacterEllipsis"/>
``` 

If you don't want this feature or if it is impossible to do, then just close this issue.

Happy coding
Tim

**Comment by punker76** [comment]
IMO this is not an issue in ControlzEx.
