### ISSUE TITLE
SystemCommands.ShowSystemMenu not DPI aware

### ISSUE THREAD

**Issue by znakeeye** [ControlzEx/ControlzEx#95]
Recall [this](https://github.com/fluentribbon/Fluent.Ribbon/issues/757) issue in Fluent Ribbon. We have found its root cause. In Fluent the `WindowSteeringHelper` class calls `ControlzEx.Windows.Shell.SystemCommands.ShowSystemMenu` which is not `DPI` aware.

On systems with DPI set to a higher value than 100%, this method will incorrectly position the system menu.

**Comment by YetAnotherCodeMaker** [comment]
… and that will prevent me from updating to the long awaited Fuent.Ribbon 7.0.0

**Comment by batzen** [comment]
The problem is not that it's not DPI aware, but that it is "double" DPI aware and adds the DPI factor twice instead of once.
